# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import gmaps
import gmaps.datasets
from pprint import pprint

# Import API key
from api_keys import g_key
gmaps.configure(api_key=g_key)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
input_path = "../WeatherPy/city_weather_data.csv"
weather_data = pd.read_csv(input_path)
weather_data

,Name,Lat,Lng,Max_Temp,Humidity,Cloudiness,Wind_Speed,Country,Date
0,Megion,61.0296,76.1136,17.01,72,12,2.69,RU,2021-08-25 20:55:20
1,Ilulissat,69.2167,-51.1000,7.01,81,75,3.60,GL,2021-08-25 20:49:31
2,Ushuaia,-54.8000,-68.3000,4.79,52,0,1.54,AR,2021-08-25 20:44:50
3,Cape Town,-33.9258,18.4232,13.40,88,75,5.14,ZA,2021-08-25 20:49:31
4,Namie,37.4833,141.0000,25.95,93,84,2.14,JP,2021-08-25 20:55:21
...,...,...,...,...,...,...,...,...,...
572,Mariehamn,60.0973,19.9348,10.92,100,0,1.03,AX,2021-08-25 20:54:01
573,Neiafu,-18.6500,-173.9833,23.38,64,40,5.14,TO,2021-08-25 20:54:01
574,Tarpon Springs,28.1461,-82.7568,35.72,56,40,0.45,US,2021-08-25 20:54:02
575,El Colomo,19.0500,-104.2500,32.99,72,62,3.64,MX,2021-08-25 20:54:02
576,Calbuco,-41.7680,-73.1273,8.56,87,97,10.57,CL,2021-08-25 20:54:03

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
center = (37.105706,	58.508362)
fig = gmaps.figure(map_type='HYBRID', zoom_level=3, center=center)
heatmap_layer = gmaps.heatmap_layer(
    weather_data[['Lat', 'Lng']], weights=weather_data['Humidity'], dissipating=False,
    max_intensity=100, point_radius = 3
)
fig.add_layer(heatmap_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [4]:
best_weather = weather_data.loc[(weather_data['Max_Temp'] <= 22) &
(weather_data['Wind_Speed'] < 8) & (weather_data['Humidity'] < 40)]
best_weather.dropna(how='any')
best_weather

,Name,Lat,Lng,Max_Temp,Humidity,Cloudiness,Wind_Speed,Country,Date
21,Mount Isa,-20.7333,139.5000,11.87,26,0,2.57,AU,2021-08-25 20:53:24
50,Salta,-24.7859,-65.4117,18.16,21,0,3.58,AR,2021-08-25 20:55:41
61,Mendoza,-32.8908,-68.8272,18.74,19,0,3.60,AR,2021-08-25 20:54:49
124,Mar del Plata,-38.0023,-57.5575,17.01,36,20,7.20,AR,2021-08-25 20:56:14
126,Mwinilunga,-11.7358,24.4293,20.68,33,9,1.82,ZM,2021-08-25 20:56:14
183,Ritchie,-29.0380,24.6028,13.56,33,18,5.49,ZA,2021-08-25 20:54:14
191,Boysun,38.2061,67.1986,21.47,21,0,3.04,UZ,2021-08-25 20:57:21
203,Changji,44.0167,87.3167,21.44,32,0,3.00,CN,2021-08-25 20:57:26
212,Mumbwa,-14.9783,27.0619,21.25,27,2,3.11,ZM,2021-08-25 20:57:30
251,Rawson,-43.3002,-65.1023,13.21,36,12,6.83,AR,2021-08-25 20:49:01
263,Thompson,55.7435,-97.8558,18.09,34,40,1.03,CA,2021-08-25 20:45:23
300,Kununurra,-15.7667,128.7333,19.25,24,4,3.00,AU,2021-08-25 20:51:29
324,San Luis,-33.2950,-66.3356,16.60,17,0,3.21,AR,2021-08-25 20:51:59
348,Diamantina,-18.2494,-43.6003,19.00,39,0,2.50,BR,2021-08-25 20:52:11
357,Kalabo,-14.9700,22.6814,20.79,27,9,2.95,ZM,2021-08-25 20:52:16
429,Viedma,-40.8135,-62.9967,14.11,30,7,6.83,AR,2021-08-25 20:52:50
463,Gravelbourg,49.8834,-106.5512,17.15,38,40,2.87,CA,2021-08-25 20:53:08
470,Wuwei,37.9281,102.6414,15.15,30,0,2.40,CN,2021-08-25 20:53:12
486,Lubango,-14.9172,13.4925,18.04,27,0,2.06,AO,2021-08-25 20:53:18
503,Putina,-15.4667,-69.4333,12.64,29,91,2.12,PE,2021-08-25 20:53:25
533,Santa Fe,-31.6333,-60.7000,20.57,20,33,2.68,AR,2021-08-25 20:53:24

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [5]:
hotel_df = best_weather.copy()
hotel_df['Hotel Name'] = None
hotel_df['Hotel Lat'] = None
hotel_df['Hotel Lng'] = None
hotel_df.head()

,Name,Lat,Lng,Max_Temp,Humidity,Cloudiness,Wind_Speed,Country,Date,Hotel Name,Hotel Lat,Hotel Lng
21,Mount Isa,-20.7333,139.5000,11.87,26,0,2.57,AU,2021-08-25 20:53:24,None,None,None
50,Salta,-24.7859,-65.4117,18.16,21,0,3.58,AR,2021-08-25 20:55:41,None,None,None
61,Mendoza,-32.8908,-68.8272,18.74,19,0,3.60,AR,2021-08-25 20:54:49,None,None,None
124,Mar del Plata,-38.0023,-57.5575,17.01,36,20,7.20,AR,2021-08-25 20:56:14,None,None,None
126,Mwinilunga,-11.7358,24.4293,20.68,33,9,1.82,ZM,2021-08-25 20:56:14,None,None,None

In [6]:
# Google Places API Query
# Set Parameters for search
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
params = {
    "radius":5000,
    "type": "lodging",
    "key": g_key
}

# Loop through Places API to find hotels
for index, row in hotel_df.iterrows():
    try:
        params['location'] = f"{row['Lat']}, {row['Lng']}"
        response = requests.get(base_url, params=params).json()
        hotels = response["results"][0]
        hotel_df.loc[index, "Hotel Name"] = hotels['name']
        hotel_df.loc[index, "Hotel Lat"] = hotels['geometry']['location']['lat']
        hotel_df.loc[index, "Hotel Lng"] = hotels['geometry']['location']['lng']
    except:
        print("No Hotels Nearby")

In [7]:
# Drop locations with no nearby hotels
hotel_df = hotel_df.dropna(how='any')
hotel_df.head()

,Name,Lat,Lng,Max_Temp,Humidity,Cloudiness,Wind_Speed,Country,Date,Hotel Name,Hotel Lat,Hotel Lng
21,Mount Isa,-20.7333,139.5000,11.87,26,0,2.57,AU,2021-08-25 20:53:24,ibis Styles Mt Isa Verona,-20.72595,139.49257
50,Salta,-24.7859,-65.4117,18.16,21,0,3.58,AR,2021-08-25 20:55:41,Hotel Alejandro I,-24.786856,-65.411953
61,Mendoza,-32.8908,-68.8272,18.74,19,0,3.60,AR,2021-08-25 20:54:49,Hotel Mendoza,-32.88882,-68.841846
124,Mar del Plata,-38.0023,-57.5575,17.01,36,20,7.20,AR,2021-08-25 20:56:14,Gran Hotel Mar del Plata,-38.001965,-57.54379
126,Mwinilunga,-11.7358,24.4293,20.68,33,9,1.82,ZM,2021-08-25 20:56:14,Kwakuwahi Lodge,-11.728386,24.440495

In [8]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{Name}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [9]:
# Add marker layer
marker_coord = hotel_df[['Hotel Lat', 'Hotel Lng']]
markers = gmaps.marker_layer(marker_coord, info_box_content=hotel_info)
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(height='420px'))

In [10]:
hotel_df.to_csv('./destinations.csv')